[build]
  command = "npm install && cp -r src/* dist/ && cp index.html dist/"
  publish = "dist"
  functions = "functions"  # Required even if empty

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
    X-Frame-Options = "DENY"